### ISSUE TITLE
Building in OSX

### ISSUE THREAD

**Issue by inpras** [chigraph/chigraph#85]
Getting following error when building in OSX

[ 73%] Building C object third_party/libgit2/CMakeFiles/git2.dir/src/unix/realpath.c.o
[ 73%] Building C object third_party/libgit2/CMakeFiles/git2.dir/deps/http-parser/http_parser.c.o
[ 74%] Linking C shared library ../../lib/libgit2.dylib
[ 74%] Built target git2
Scanning dependencies of target chigraphruntime
[ 75%] Generating arc.c.bc for runtime...
error: unable to open output file '/Users/prasannainamdar/temp/chigraph/build/lib/runtime/runtime.obj/arc.c.bc': 'No such file or directory'
1 error generated.
make[2]: *** [lib/runtime/runtime.obj/arc.c.bc] Error 1
make[1]: *** [lib/runtime/CMakeFiles/chigraphruntime.dir/all] Error 2
make: *** [all] Error 2

Can some one please let me know what am I missing?

**Comment by binbinmeng** [comment]
Have you solved this issue ? I also met with same error.

**Comment by inpras** [comment]
Nope, this never got resolved for me

**Comment by binbinmeng** [comment]
I solved it by "mkdir runtime.obj"  directory manually.
