### ISSUE TITLE
-- LLDB library: LLDB_LIBRARY-NOTFOUND   on Mac

### ISSUE THREAD

**Issue by panue** [chigraph/chigraph#88]

**Comment by panue** [comment]
-- LLDB library: LLDB_LIBRARY-NOTFOUND
CMake Error at lib/debugger/CMakeLists.txt:14 (message):
 Failed to find the lldb library in /Users/tools/LLVM/build/lib

**Comment by russelltg** [comment]
Did you build LLDB with LLVM?

**Comment by panue** [comment]
I forget to build the lldb
